### ISSUE TITLE
FileNotFoundError when running python eval_ploicy.py

### ISSUE THREAD

**Issue by yashiro32** [BerkeleyAutomation/AlphaGarden#29]
FileNotFoundError: [Errno 2] No such file or directory: '/Users/williamwong/Downloads/scaled_orig_placement'

**Comment by w07wong** [comment]
You can either comment this line out for random seed initialization, or run [final_find.py](https://github.com/BerkeleyAutomation/AlphaGarden/blob/master/Simulator/simulator/final_find.py) to generate your own seed placement file. Once generated, replace that path with your own.
