### ISSUE TITLE
Examples on using Simulator for custom reinforcement learning implementations?

### ISSUE THREAD

**Issue by yashiro32** [BerkeleyAutomation/AlphaGarden#30]
Are there any examples or documentations on using this Simulator as an OpenAI Gym Environment for our own custom reinforcement learning implementations? Such as coming out with our own automation policies?

**Comment by w07wong** [comment]
Thanks for your interest in our work. This simulator is a gym environment and you can interact with it through the method [here](https://github.com/BerkeleyAutomation/AlphaGarden/blob/master/Learning/gym_simalphagarden/agenv/simalphagarden/envs/simalphagarden_env.py). However, the way we usually interact with the enviornment is through [SimAlphaGardenWrapper.py](https://github.com/BerkeleyAutomation/AlphaGarden/blob/dd4b7018e533560cf26b9fa5e4978296ac06006b/Simulator/simulator/SimAlphaGardenWrapper.py).

Examples of initializing the environment can be found in eval_policy.py [here](https://github.com/BerkeleyAutomation/AlphaGarden/blob/master/Learning/eval_policy.py#L34-L57) and [data_collection.py](https://github.com/BerkeleyAutomation/AlphaGarden/blob/master/Learning/data_collection.py#L20-L43). You can see an example of how we interact with this environment ('env' variable) [here](https://github.com/BerkeleyAutomation/AlphaGarden/blob/master/Learning/data_collection.py#L50-L75).

If you want to come up with your own automation policies, you can define policies like we do in the [baselines](https://github.com/BerkeleyAutomation/AlphaGarden/tree/dd4b7018e533560cf26b9fa5e4978296ac06006b/Simulator/simulator/baselines) sub-folder and import them similar to the other policies there.
